/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_junechiu_interview_jni_CCallJava */

#ifndef _Included_cn_junechiu_interview_jni_CCallJava
#define _Included_cn_junechiu_interview_jni_CCallJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_junechiu_interview_jni_CCallJava
 * Method:    callbackAdd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_junechiu_interview_jni_CCallJava_callbackAdd
  (JNIEnv *, jobject);

/*
 * Class:     cn_junechiu_interview_jni_CCallJava
 * Method:    callbackHelloFromJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_junechiu_interview_jni_CCallJava_callbackHelloFromJava
  (JNIEnv *, jobject);

/*
 * Class:     cn_junechiu_interview_jni_CCallJava
 * Method:    callbackPrintString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_junechiu_interview_jni_CCallJava_callbackPrintString
  (JNIEnv *, jobject);

/*
 * Class:     cn_junechiu_interview_jni_CCallJava
 * Method:    callbackSayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_junechiu_interview_jni_CCallJava_callbackSayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
