/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include<string.h>
/* Header for class cn_junechiu_interview_jni_HelloJni */

#include <android/log.h>
#define LOG_TAG "helloJNI"
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

#ifndef _Included_cn_junechiu_interview_jni_HelloJni
#define _Included_cn_junechiu_interview_jni_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_junechiu_interview_jni_HelloJni
 * Method:    getStrFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_junechiu_interview_jni_HelloJni_getStrFromC
  (JNIEnv *, jobject);

/*
 * Class:     cn_junechiu_interview_jni_HelloJni
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cn_junechiu_interview_jni_HelloJni_sum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cn_junechiu_interview_jni_HelloJni
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_junechiu_interview_jni_HelloJni_sayHello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_junechiu_interview_jni_HelloJni
 * Method:    increaseArrayEles
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_junechiu_interview_jni_HelloJni_increaseArrayEles
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
