/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include<string.h>
/* Header for class cn_junechiu_interview_jni_CheckPasswd */

#ifndef _Included_cn_junechiu_interview_jni_CheckPasswd
#define _Included_cn_junechiu_interview_jni_CheckPasswd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_junechiu_interview_jni_CheckPasswd
 * Method:    checkPwd
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_junechiu_interview_jni_CheckPasswd_checkPwd
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
